export const clinic = { name: "Cusp Dental Studio", city: "Bengaluru", address: "", phone: "", whatsapp: "", email: "", demo: true, hours: { weekdays: [9, 19], saturday: [9, 14] } };
export const treatments = [
  { id: "checkup", title: "Everyday care", category: "Maintain", price: 900, unit: "consultation", short: "A good place to start. A clear picture of your dental health.", detail: "Start with your concerns and a dental examination. Your dentist can explain which next steps, if any, make sense for you.", includes: ["Discuss your concerns", "Review oral health", "Agree on next steps"], note: "Cleaning, imaging and further treatment are quoted separately." },
  { id: "whitening", title: "Teeth whitening", category: "Brighten", price: 8900, unit: "indicative treatment", short: "Explore a brighter smile that still feels like you.", detail: "Discuss the shade you have in mind and the whitening options suitable for your teeth. An examination comes first; results and suitability vary.", includes: ["Shade and sensitivity discussion", "Suitability assessment", "Options and aftercare explained"], note: "An examination is needed before a dentist recommends whitening." },
  { id: "aligners", title: "Clear aligners", category: "Align", price: 89000, unit: "indicative course", short: "A considered route to straighter teeth, step by step.", detail: "Explore whether clear aligners fit your goals. An orthodontic assessment informs a proposed plan, estimated duration and review schedule.", includes: ["Discuss alignment goals", "Review assessment requirements", "Understand the proposed schedule"], note: "Duration and cost depend on the assessment. No treatment timeline is guaranteed." },
  { id: "implants", title: "Dental implants", category: "Restore", price: 35000, unit: "indicative implant", short: "Understand your options for replacing a missing tooth.", detail: "Talk through replacement options, including whether an implant assessment is appropriate. Your complete plan should explain all stages and costs.", includes: ["Discuss replacement options", "Review assessment needs", "Receive a staged estimate"], note: "Crown, imaging and additional procedures may cost extra." },
  { id: "rootcanal", title: "Root canal care", category: "Restore", price: 6500, unit: "indicative treatment", short: "Get answers about a tooth that needs attention.", detail: "A dentist examines the tooth and discusses findings before recommending treatment. Ask about the procedure, comfort options and any follow-up restoration.", includes: ["Examine the affected tooth", "Explain findings and alternatives", "Discuss restoration and follow-up"], note: "Pricing depends on the tooth and complexity. A final restoration may be quoted separately." },
  { id: "veneers", title: "Smile design", category: "Brighten", price: 18000, unit: "indicative veneer", short: "Shape, shade and proportion, considered together.", detail: "Discuss the changes you are considering, including alternative approaches and the implications of veneers. A consultation helps you make an informed choice.", includes: ["Discuss aesthetic goals", "Explore available approaches", "Review maintenance and costs"], note: "Ask your dentist about preparation, alternatives and long-term maintenance." },
];
export type Treatment = (typeof treatments)[number];
export const money = (amount: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(amount);
export const asset = (file: string) => `${import.meta.env.BASE_URL || "/"}${file}`;
export const reviews = [
  { name: "Amara W.", treatment: "Everyday care", quote: "For once, I understood the plan before I had to make a decision. That made all the difference." },
  { name: "Tobias L.", treatment: "Clear aligners", quote: "I had a lot of questions. Having the time to ask them made the whole visit feel easier." },
  { name: "Reina O.", treatment: "Smile design", quote: "I wanted a subtle change. It was reassuring to talk through the options without feeling rushed." },
];
export const faqs = [
  ["What happens at my first visit?", "We start with your questions, review your concerns and explain the examination. You can discuss options and costs before deciding what to do next."],
  ["Can I come in if I’m nervous?", "Yes. Mention your concerns when speaking with the practice so the team can discuss how to make the visit more comfortable."],
  ["Are these prices final?", "The amounts shown are sample starting prices for this concept practice. A real treatment estimate depends on an examination and should specify inclusions and additional costs."],
  ["Does this website confirm appointments?", "This is a working website demonstration. Explore the appointment flow and download a visit plan; nothing is sent and no appointment is booked."],
];
